glx/windows: Fix compilation of driwindows_glx after driscreen changed from pointer to member
> ../src/glx/driwindows_glx.c: In function ‘driwindows_create_context’:
> ../src/glx/driwindows_glx.c:122:8: error: wrong type argument to unary exclamation mark
>   122 |    if (!psc->base.driScreen)
>       |        ^
> ../src/glx/driwindows_glx.c: In function ‘driwindows_create_context_attribs’:
> ../src/glx/driwindows_glx.c:196:8: error: wrong type argument to unary exclamation mark
>   196 |    if (!psc->base.driScreen || !config_base)
>       |        ^

Since the driScreen member of driwindows_screen is now a struct, not a
pointer, checking it for non-NULL-ness like this is an error.

Fixes: d9380011dc81 ("mesa_interface: replace opaque __DRIscreen with struct dri_screen everywhere")
Signed-off-by: Jon Turney <jon.turney@dronecode.org.uk>
(cherry picked from commit 464daf978e1a8c35e9a6bbc8e5b9d1996d0c013f)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/41676>