tu: Fix passing tmp arrays to tu_desc_set_swiz/fdl6_buffer_view_init
../src/freedreno/vulkan/tu_clear_blit.cc:3664:1:   required from here
../src/freedreno/vulkan/tu_clear_blit.cc:1274:26: error: taking address of temporary array
 1274 |    tu_desc_set_swiz<CHIP>(desc, tu_swiz(X, Y, Z, W));

Fixes: e173ee04c09 ("tu: Extract out descriptor helpers")

Signed-off-by: Danylo Piliaiev <dpiliaiev@igalia.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39198>