meson: add dependency on android-hwvulkan-headers
When building without the android-stub and with meson2hermetic,
we need to find vulkan headers somewhere.

Without this, the following error is observed:

vulkan/runtime/vk_android.c:46:10: fatal error: 'hardware/hwvulkan.h' file not found
   46 | #include <hardware/hwvulkan.h>
      |          ^~~~~~~~~~~~~~~~~~~~~

This provided via the hwvulkan_headers target in:

    ${AOSP}/frameworks/native/vulkan

Reviewed-by: Eric Engestrom <eric@igalia.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/39279>