vulkan: fix build dependency issue with generated files
On machines with many cores, you can run into that issue :

../mesa-9999/src/vulkan/overlay-layer/overlay.cpp:42:10: fatal error: vk_enum_to_str.h: No such file or directory

v2: Move declare_dependency around (Eric)

Signed-off-by: Lionel Landwerlin <lionel.g.landwerlin@intel.com>
Reported-by: Jan Ziak
Cc: <mesa-stable@lists.freedesktop.org>
Reviewed-by: Eric Engestrom <eric.engestrom@intel.com>
Rebased by Dylan

Conflicts:
	src/amd/vulkan/meson.build
        src/freedreno/vulkan/meson.build
        src/intel/vulkan/meson.build
        src/vulkan/overlay-layer/meson.build
        src/vulkan/wsi/meson.build