util: Fix unmatched parenthesis.
Fixes MSVC build error introduced with commit
3d359cb93733397e1f34ab040be6d489495b5991.

src\gallium\auxiliary\util\u_cpu_detect.c(286) : fatal error C1012: unmatched parenthesis : missing '('

Signed-off-by: Vinson Lee <vlee@freedesktop.org>