radv: Fix gnu-empty-initializer errors in 65f54b9a
Fixes the following building errors:

../src/amd/vulkan/radv_rra.c:1369:43: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
      struct radv_bvh_stats_gfx12 stats = {};
                                          ^
../src/amd/vulkan/radv_rra.c:1376:45: error: use of GNU empty initializer extension [-Werror,-Wgnu-empty-initializer]
      struct radv_bvh_stats_gfx10_3 stats = {};
                                            ^
2 errors generated.

Fixes: 65f54b9a ("radv: Add an option for dumping BVH stats")
(cherry picked from commit dfca417db88dcb54fbcef0492136c593ed6fafb5)

Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/41104>