Revert "Implement EGL API for MESA_query_driver"
This reverts commit dc0a270bb5b17be9b7752352485871903ead8e82.

with default warnings configuration, this commit generates:

   ../src/egl/main/eglapi.c:2654:1: error: no previous prototype for
            ‘eglGetDisplayDriverConfig’ [-Werror=missing-prototypes]