Revert "glsl: reject image qualifiers with non-image types inside uniform blocks"
This reverts commit eef612796f7761a00a302dfb46c11782485cd593.

This causes lots of ES 3.1 CTS tests to fail to compile a bit of code
like:

   layout(binding = 0) buffer InOut
   {
        highp uint inputValues[384];
        highp uint outputValues[384];
        coherent highp uint groupValues[64];      <-----
   } sb_inout;

   error: memory qualifiers may only be applied to images