gallium/radeon: fix missing winsys include in pipe-loader.
The commit 726f22be4ec9d6c409595c116fb8ca9c6742370e introduced a build
error:

error: dereferencing pointer to incomplete type

This patch fixes this issue in all the affected files.

Reviewed-by: Tom Stellard <thomas.stellard@amd.com>