ci/vkd3d: Disable Werror for vkd3d-proton
These warnings were causing the arm64 build to fail:

../../vkd3d-proton-src/libs/vkd3d/command.c: In function 'd3d12_shared_fence_set_native_sync_handle_on_completion_explicit':
../../vkd3d-proton-src/libs/vkd3d/command.c:1772:27: error: assignment to 'const uint64_t *' {aka 'const long unsigned int *'} from incompatible pointer type 'UINT64 *' {aka 'long long unsigned int *'} [-Wincompatible-pointer-types]
 1772 |         wait_info.pValues = &value;
      |                           ^

Signed-off-by: Valentine Burley <valentine.burley@collabora.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/35853>