anv: add missing regerror stub
Otherwise,

../src/intel/vulkan/anv_util.c:375:10:
   error: implicit declaration of function 'regerror' [-Wimplicit-function-declaration]
       regerror(compile_res, &re, compile_err, 256);

is observed with the NO_REGEX path.

Reviewed-by: Ian Romanick <ian.d.romanick@intel.com>
Part-of: <https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/44807>