configure.ac: require libdrm 2.4.66 for drmGetDevice
since abd5385921bb78b93bdfcb32c52203f02c9be3d4
src/gallium/winsys/amdgpu/drm/amdgpu_winsys.c no longer compiles:
error: unknown type name ‘drmDevicePtr’