mesa/sso: Fix typo of 'unsigned'.
Fix build error introduced with commit c0e8086a2a90fd3750850ca890c3bd6248c0fe11.

  CC       pixeltransfer.lo
main/pipelineobj.c: In function '_mesa_delete_pipeline_object':
main/pipelineobj.c:59:4: error: unknown type name 'unsinged'
    unsinged i;
    ^

Signed-off-by: Vinson Lee <vlee@freedesktop.org>